server:
  port: 8080

#spring
spring:
  application:
    name: cms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle:  10
    maxActive: 20
    maxWait: 60000
    keepAlive: true
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 60000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 15
    maxPoolPreparedStatementPerConnectionSize: 15
    useGlobalDataSourceStat: true
    asyncInit: true
    filters: stat,log4j2
    logSlowSql: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    removeAbandoned: true
    removeAbandonedTimeout: 30
    logAbandoned: true
    druid:    #使用log4j2排除
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

#mybatis
mabatis:
  type-aliases-package: cn.cityworks.cms.dao.*

#log4j2
logging:
  config: classpath:log4j2.yml